name: Build
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Build & Publish Docker image
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/riscv64
          tags: ${{ vars.DOCKERHUB_USERNAME }}/archriscv:latest
      - name: Test
        run: |
          docker run \
            --rm \
            --platform linux/riscv64 \
            ${{ vars.DOCKERHUB_USERNAME }}/archriscv:latest \
            pacman -Syy
